### ISSUE TITLE
Profile Image not loading from Clerk

### ISSUE THREAD

**Issue by DataHawker** [AntonioErdeljac/next13-discord-clone#13]
Google account - Profile image shows in the chat. Other accounts, even with image uploaded in clerk, shows the default image. 

<img width="398" alt="Screenshot 2023-09-05 at 9 55 42 AM" src="https://github.com/AntonioErdeljac/next13-discord-clone/assets/106617192/e2fc5339-22b2-4e84-9c59-ba061a9368eb">

**Comment by KneesDev** [comment]
Profile pictures on chat are saved in the database as a URL, however Clerk generates a new URL for every profile picture uploaded instead of replacing the current one with the new profile picture so you'll have to manually update the profile picture URL for the user in the database. The bottom-left "button" is a Clerk component so it auto updates the profile picture URL for that component.
